CREATE TABLE IF NOT EXISTS layers (
  layer_id VARCHAR(64) NOT NULL,
  name VARCHAR(128) NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  ui_display_order INT NOT NULL DEFAULT 0,
  visible_default TINYINT(1) NOT NULL DEFAULT 1,
  opacity_default DOUBLE NOT NULL DEFAULT 1.0,
  z_base DOUBLE NOT NULL DEFAULT 0.0,
  transform_kind VARCHAR(32) NOT NULL,
  affine_a DOUBLE NULL,
  affine_b DOUBLE NULL,
  affine_tx DOUBLE NULL,
  affine_c DOUBLE NULL,
  affine_d DOUBLE NULL,
  affine_ty DOUBLE NULL,
  tileset_manifest_url VARCHAR(512) NOT NULL,
  tile_url_template VARCHAR(512) NOT NULL,
  tileset_version VARCHAR(64) NOT NULL DEFAULT '',
  tile_px INT NOT NULL DEFAULT 512,
  max_level INT NOT NULL DEFAULT 0,
  y_flip TINYINT(1) NOT NULL DEFAULT 0,
  request_weight DOUBLE NOT NULL DEFAULT 1.0,
  pick_mode VARCHAR(32) NOT NULL DEFAULT 'none',
  layer_kind VARCHAR(32) NOT NULL DEFAULT 'tiled_raster',
  vector_source_url VARCHAR(512) NULL,
  vector_source_revision VARCHAR(128) NULL,
  vector_geometry_space VARCHAR(32) NOT NULL DEFAULT 'map_pixels',
  vector_style_mode VARCHAR(64) NOT NULL DEFAULT 'feature_property_palette',
  vector_feature_id_property VARCHAR(128) NULL,
  vector_color_property VARCHAR(128) NULL,
  lod_target_tiles INT NOT NULL DEFAULT 220,
  lod_hysteresis_hi DOUBLE NOT NULL DEFAULT 280.0,
  lod_hysteresis_lo DOUBLE NOT NULL DEFAULT 160.0,
  lod_margin_tiles INT NOT NULL DEFAULT 1,
  lod_enable_refine TINYINT(1) NOT NULL DEFAULT 0,
  lod_refine_debounce_ms INT NOT NULL DEFAULT 0,
  lod_max_detail_tiles INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (layer_id)
);

CREATE TABLE IF NOT EXISTS layer_configs (
  map_version_id VARCHAR(64) NOT NULL,
  layer_id VARCHAR(64) NOT NULL,
  enabled_override TINYINT(1) NULL,
  visible_default_override TINYINT(1) NULL,
  opacity_default_override DOUBLE NULL,
  z_base_override DOUBLE NULL,
  tileset_manifest_url_override VARCHAR(512) NULL,
  tile_url_template_override VARCHAR(512) NULL,
  tileset_version_override VARCHAR(64) NULL,
  vector_source_url_override VARCHAR(512) NULL,
  vector_source_revision_override VARCHAR(128) NULL,
  max_level_override INT NULL,
  request_weight_override DOUBLE NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (map_version_id, layer_id),
  KEY idx_layer_configs_layer (layer_id)
);

INSERT INTO layers (
  layer_id, name, enabled, ui_display_order, visible_default, opacity_default, z_base,
  transform_kind, affine_a, affine_b, affine_tx, affine_c, affine_d, affine_ty,
  tileset_manifest_url, tile_url_template, tileset_version,
  tile_px, max_level, y_flip, request_weight, pick_mode,
  layer_kind, vector_source_url, vector_source_revision, vector_geometry_space, vector_style_mode,
  vector_feature_id_property, vector_color_property,
  lod_target_tiles, lod_hysteresis_hi, lod_hysteresis_lo, lod_margin_tiles,
  lod_enable_refine, lod_refine_debounce_ms, lod_max_detail_tiles
) VALUES
  (
    'minimap', 'Minimap', 1, 0, 1, 1.0, 0.0,
    'affine_to_world', 100.0, 0.0, 0.0, 0.0, 100.0, 0.0,
    '/images/tiles/minimap/v1/tileset.json', '/images/tiles/minimap/v1/{level}/rader_{x}_{y}.png', 'v1',
    128, 6, 1, 1.0, 'none',
    'tiled_raster', NULL, NULL, 'map_pixels', 'feature_property_palette', NULL, NULL,
    256, 320.0, 192.0, 2,
    1, 150, 256
  ),
  (
    'zone_mask', 'Zone Mask', 1, 10, 1, 0.35, 10.0,
    'identity_map_space', NULL, NULL, NULL, NULL, NULL, NULL,
    '/images/tiles/mask/{map_version}/tileset.json', '/images/tiles/mask/{map_version}/{level}/{x}_{y}.png', 'v1',
    512, 0, 0, 0.7, 'exact_tile_pixel',
    'tiled_raster', NULL, NULL, 'map_pixels', 'feature_property_palette', NULL, NULL,
    300, 360.0, 220.0, 1,
    0, 0, 0
  )
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  enabled = VALUES(enabled),
  ui_display_order = VALUES(ui_display_order),
  visible_default = VALUES(visible_default),
  opacity_default = VALUES(opacity_default),
  z_base = VALUES(z_base),
  transform_kind = VALUES(transform_kind),
  affine_a = VALUES(affine_a),
  affine_b = VALUES(affine_b),
  affine_tx = VALUES(affine_tx),
  affine_c = VALUES(affine_c),
  affine_d = VALUES(affine_d),
  affine_ty = VALUES(affine_ty),
  tileset_manifest_url = VALUES(tileset_manifest_url),
  tile_url_template = VALUES(tile_url_template),
  tileset_version = VALUES(tileset_version),
  tile_px = VALUES(tile_px),
  max_level = VALUES(max_level),
  y_flip = VALUES(y_flip),
  request_weight = VALUES(request_weight),
  pick_mode = VALUES(pick_mode),
  layer_kind = VALUES(layer_kind),
  vector_source_url = VALUES(vector_source_url),
  vector_source_revision = VALUES(vector_source_revision),
  vector_geometry_space = VALUES(vector_geometry_space),
  vector_style_mode = VALUES(vector_style_mode),
  vector_feature_id_property = VALUES(vector_feature_id_property),
  vector_color_property = VALUES(vector_color_property),
  lod_target_tiles = VALUES(lod_target_tiles),
  lod_hysteresis_hi = VALUES(lod_hysteresis_hi),
  lod_hysteresis_lo = VALUES(lod_hysteresis_lo),
  lod_margin_tiles = VALUES(lod_margin_tiles),
  lod_enable_refine = VALUES(lod_enable_refine),
  lod_refine_debounce_ms = VALUES(lod_refine_debounce_ms),
  lod_max_detail_tiles = VALUES(lod_max_detail_tiles);

INSERT INTO layer_configs (
  map_version_id, layer_id,
  z_base_override,
  tileset_manifest_url_override, tile_url_template_override, tileset_version_override,
  vector_source_url_override, vector_source_revision_override
) VALUES
  ('v1', 'minimap', 0.0, '/images/tiles/minimap/v1/tileset.json', '/images/tiles/minimap/v1/{level}/rader_{x}_{y}.png', 'v1', NULL, NULL),
  ('v1', 'zone_mask', 10.0, '/images/tiles/mask/v1/tileset.json', '/images/tiles/mask/v1/{level}/{x}_{y}.png', 'v1', NULL, NULL)
ON DUPLICATE KEY UPDATE
  z_base_override = VALUES(z_base_override),
  tileset_manifest_url_override = VALUES(tileset_manifest_url_override),
  tile_url_template_override = VALUES(tile_url_template_override),
  tileset_version_override = VALUES(tileset_version_override),
  vector_source_url_override = VALUES(vector_source_url_override),
  vector_source_revision_override = VALUES(vector_source_revision_override);
