use std::{fs, io::Write, path::Path};

fn main() {
    let output_path = Path::new("src/zones/zone_names.rs");

    let bookmark_dir = Path::new("bdo-fish-waypoints/Bookmark");
    let mut zone_names = Vec::new();

    if let Ok(entries) = fs::read_dir(bookmark_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                if let Some(name) = path.file_name().and_then(|s| s.to_str()) {
                    zone_names.push(name.to_string());
                }
            }
        }
    }

    zone_names.sort();

    let mut file = fs::File::create(&output_path).unwrap();
    writeln!(file, "// THIS FILE IS AUTOGENERATED AT BUILD TIME").unwrap();
    writeln!(file, "pub static ZONE_NAMES: &[&str] = &[").unwrap();
    for zone in zone_names {
        writeln!(file, "    {:?},", zone).unwrap();
    }
    writeln!(file, "];").unwrap();
}
