name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
    paths:
      - '.github/workflows/gh-pages.yml'
      - 'site/**'
jobs:
  deploy:
    defaults:
      run:
        working-directory: site
    environment:
      name: github-pages
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Change if you need git info
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun run pre-build

      - name: Setup Zine
        uses: kristoff-it/setup-zine@v1
        with:
          version: v0.11.0

      - name: Release
        run: zine release

      - run: bun run pre-build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site/public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
