name: github pages

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Set a branch to deploy
jobs:
  deploy:
    environment:
      name: github-pages
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Change if you need git info
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        shell: bash
        run: nix profile add nixpkgs#devenv
      - name: Build site in devenv
        shell: devenv shell bash -- -e {0}
        run: |
          cd site
          bun install
          bun run pre-build
          zine release
          bun run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site/public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
